services:
  - type: web
    name: shopbanskin
    env: node
    buildCommand: NODE_ENV=development npm install && cd client && NODE_ENV=development npm install && npx vite build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
